version: '3'
services:
  postgres:
    image: huecker.io/library/postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5555:5432'
    restart: always
    networks:
      - pg-net

  pgadmin:
    image: huecker.io/dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - pg-net

  app:
    build: .
    ports:
      - 8432:8000
    restart: always
    depends_on:
      - postgres
    networks:
      - pg-net
    env_file:
      - .env

  metabase:
    image: huecker.io/metabase/metabase
    ports:
      - 3333:3000
    networks:
      - pg-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-net: