version: '3'
services:
  postgres:
    image: library/postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - '5555:5432'
    restart: always
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: xxx
    depends_on:
      - postgres
    networks:
      - pg-net

  app:
    build: .
    ports:
      - 8432:8000
    restart: always
    depends_on:
      - postgres
    networks:
      - pg-net

  metabase:
    image: metabase/metabase
    ports:
      - 3333:3000
    networks:
      - pg-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-net: